### ISSUE TITLE
Local impress.js vs online

### ISSUE THREAD

**Issue by skylark1848** [wmh/circular-slides-generator#1]
I found I had to change the sript in the html to local

```
 <script src="js/impress.js"></script>
 <script>impress().init();</script>
```

It will not work with the https://cdnjs.cloudflare.com/ajax/libs/impress.js/0.5.3/impress.js, therefore browser displays slides as one column, transitions will not work either.

**Comment by wmh** [comment]
Yeah, it seems browser block the external JavaScript from local file system. I'll add a notice to the generator page. Thanks for reporting this.

**Comment by skylark1848** [comment]
No problem, thanks for starting the project, helped me a lot with using impress.js :)
